name: Run GitHub Trend Fetcher

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Ensure compatibility with dependencies

    - name: Upgrade Pip & Install Dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Run main script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DB_CONNECTION_NAME: ${{ secrets.DB_CONNECTION_NAME }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: python main.py
